<a href="https://colab.research.google.com/github/jessicalewinter/deep-learning-specialization/blob/main/course-notebooks/software-engineering/pytorch-tutorials/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
# Scalar
scalar = torch.tensor(7)
print(f"quantity of dimensions: {scalar.ndim}")
print(f"quantity of items: {scalar.item()}")

print("gdgd")

quantity of dimensions: 0
quantity of items: 7
gdgd


In [ ]:
# Vector
vector = torch.tensor([7, 7])
print(f"quantity of dimensions: {vector.ndim}")
print(f"shape: {vector.shape}")

quantity of dimensions: 1
shape: torch.Size([2])


In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8, 7],
                       [9, 10, 7],
                       [11, 12, 7]])
print(f"quantity of dimensions: {MATRIX.ndim}")
print(f"shape: {MATRIX.shape}")

quantity of dimensions: 2
shape: torch.Size([3, 3])


In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 5]],
                       MATRIX])
print(f"quantity of dimensions: {TENSOR.ndim}")
print(f"shape: {TENSOR.shape}")

quantity of dimensions: 3
shape: torch.Size([2, 3, 3])


In [ ]:
TENSOR2 = torch.tensor([[[0]]])
TENSOR2.shape

torch.Size([1, 1, 1])

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 3, 4))
random_tensor, random_tensor.dtype, random_tensor.shape

(tensor([[[0.9809, 0.5423, 0.7062, 0.0051],
          [0.4662, 0.9974, 0.7141, 0.4845],
          [0.5912, 0.6778, 0.7170, 0.3431]],
 
         [[0.7594, 0.6416, 0.7060, 0.2365],
          [0.1417, 0.8128, 0.1879, 0.7026],
          [0.0973, 0.9895, 0.7001, 0.1112]],
 
         [[0.8062, 0.1316, 0.5693, 0.2955],
          [0.5553, 0.4811, 0.2786, 0.8363],
          [0.9017, 0.2019, 0.0721, 0.7860]]]),
 torch.float32,
 torch.Size([3, 3, 4]))

In [ ]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
print(f"quantity of dimensions: {random_image_size_tensor.ndim}")
print(f"shape: {random_image_size_tensor.shape}")
random_image_size_tensor


quantity of dimensions: 3
shape: torch.Size([224, 224, 3])


tensor([[[0.0482, 0.2398, 0.2479],
         [0.5299, 0.9771, 0.0707],
         [0.4455, 0.9423, 0.2335],
         ...,
         [0.1191, 0.6943, 0.4183],
         [0.6226, 0.6674, 0.3548],
         [0.5873, 0.2418, 0.8783]],

        [[0.6123, 0.5250, 0.5539],
         [0.8684, 0.3641, 0.6153],
         [0.8315, 0.4957, 0.0068],
         ...,
         [0.0433, 0.9742, 0.6351],
         [0.3129, 0.5605, 0.2891],
         [0.2939, 0.5250, 0.4850]],

        [[0.4258, 0.0366, 0.9910],
         [0.6877, 0.4573, 0.3739],
         [0.4419, 0.1426, 0.8839],
         ...,
         [0.4301, 0.4509, 0.5525],
         [0.1180, 0.6764, 0.6257],
         [0.1024, 0.6901, 0.1230]],

        ...,

        [[0.0427, 0.2868, 0.3568],
         [0.0386, 0.7311, 0.7195],
         [0.4165, 0.8298, 0.2164],
         ...,
         [0.3178, 0.5397, 0.8673],
         [0.7382, 0.4510, 0.2632],
         [0.8643, 0.2300, 0.0837]],

        [[0.1381, 0.4356, 0.8091],
         [0.0653, 0.7980, 0.3182],
         [0.

In [ ]:
zeros = torch.zeros(size=(3, 4))

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype, ones.shape

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32,
 torch.Size([3, 4]))

In [ ]:
# Create a range of values from 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten, zero_to_ten.shape, zero_to_ten.dtype

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]), torch.int64)

In [ ]:
# create a tensor filled with zeros with the size as the input tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Tensor datatypes
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=torch.float64,
    device=None,
    requires_grad=False
    )

float_32_tensor.dtype

torch.float64

In [17]:
# Getting information from tensors

## Create a tensor
some_tensor = torch.rand(3, 4)

## Get details of the tensor
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.3591, 0.3827, 0.3221, 0.1419],
        [0.4870, 0.7960, 0.1346, 0.0039],
        [0.8754, 0.0689, 0.4131, 0.9235]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device of tensor: cpu
